### ISSUE TITLE
502 Bad Gateway in home page api.cgi

### ISSUE THREAD

**Issue by hubmon** [kszere/Xiaomi-Dafang-API#1]
Do I need to keep the files from Elias firmware_mod? Or only your firmware_mod.

Also when attempt to open http://192.168.1.122/cgi-bin/api.cgi
Get this:
502 Bad Gateway
The CGI was not CGI/1.1 compliant.

**Comment by kszere** [comment]
Please check [http://192.168.1.122/cgi-bin/api.cgi?action=systeminfo](http://192.168.1.122/cgi-bin/api.cgi?action=systeminfo)
Without GET param server on camera say's 502 Bad Gateway, with GET param it should work

I added in the new version new param:
- ?action=check_light
- ?action=systeminfo. 

: )

**Comment by kszere** [comment]
From v0.0.4 Beta, API view Home Page with information.
![image](https://user-images.githubusercontent.com/7155051/36066969-21a41f3c-0eb4-11e8-9256-53ba670cb658.png)
