### ISSUE TITLE
How to use authentication without api_key

### ISSUE THREAD

**Issue by marciogranzotto** [kszere/Xiaomi-Dafang-API#4]
Since `api_key` is not yet implemented, how should we use the authorization with this API requests?

**Comment by kszere** [comment]
This not implementation for in the moment.

śr., 8 sty 2020, 13:57 użytkownik Marcio Granzotto Rodrigues <
notifications@github.com> napisał:

**Comment by marciogranzotto** [comment]
No problem.
I figured out I need the user and password in the URL like:
```
https://USER:PASSWORD@192.168.1.125/cgi-bin/api.cgi?action=reboot
```
